--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2026/1/24 4:19:59
-- Server version: 10.6.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Dumping data for table realm
--
INSERT INTO realm VALUES
('538f2e4100eacdb5d696ece81b50b0cf', '@cu', 'dfea5a83-3d82-4000-aee3-fc41b2c68b9d');

-- 
-- Dumping data for table sidebar_tree
--
INSERT INTO sidebar_tree VALUES
('6020f1ba-2134-4ab3-ac28-c3a73b85dd00', '上网账号', 'dfea5a83-3d82-4000-aee3-fc41b2c68b9d', 4, NULL),
('62965821-1e28-4b5d-b6c4-82f1823e1c87', '在线用户', 'dfea5a83-3d82-4000-aee3-fc41b2c68b9d', 8, NULL),
('81034dad-ccc5-4bb9-8020-9424bc5b0eac', '根节点', '81034dad-ccc5-4bb9-8020-9424bc5bccc', 1, 'admin'),
('938a1862-9a20-489f-9cc7-bc183cd2fa23', '认证日志', 'dfea5a83-3d82-4000-aee3-fc41b2c68b9d', 9, NULL),
('9a48508d-dbec-481c-8527-b2a990af1e66', '上网记录', 'dfea5a83-3d82-4000-aee3-fc41b2c68b9d', 5, NULL),
('dfea5a83-3d82-4000-aee3-fc41b2c68b9d', '广电网络', 'fe3b0289-04b4-49da-8002-f67b00143a1f', 0, 'admin'),
('fe3b0289-04b4-49da-8002-f67b00143a1f', '有线网络', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 1, 'admin');

-- 
-- Dumping data for table radreply
--
-- Table radius.radreply does not contain any data (it is empty)

-- 
-- Dumping data for table radpostauth
--
-- Table radius.radpostauth does not contain any data (it is empty)

-- 
-- Dumping data for table radcheck
--
-- Table radius.radcheck does not contain any data (it is empty)

-- 
-- Dumping data for table online_user
--
-- Table radius.online_user does not contain any data (it is empty)

-- 
-- Dumping data for table offline_user
--
-- Table radius.offline_user does not contain any data (it is empty)

-- 
-- Dumping data for table node_statistic
--
INSERT INTO node_statistic VALUES
('81034dad-ccc5-4bb9-8020-9424bc5b0eac', 6, 0, 0),
('dfea5a83-3d82-4000-aee3-fc41b2c68b9d', 6, 0, 0),
('fe3b0289-04b4-49da-8002-f67b00143a1f', 6, 0, 0);

-- 
-- Dumping data for table nas
--
INSERT INTO nas VALUES
(105, '*', 'any', 'other', 0, '3atest@123456789', '3atest@123456789', 1, '', '', 'radius client');

-- 
-- Dumping data for table admin
--
INSERT INTO admin VALUES
('admin', '123456', '81034dad-ccc5-4bb9-8020-9424bc5b0eac', 'admin', NULL, NULL);

-- 
-- Dumping data for table account_info
--
INSERT INTO account_info(id, user_name, realm, user_password, auth_mode, is_frozen, admin_name, valid_date, expire_date, modify_date, simual_use_limit, byte_remain, second_remain, max_session_timeout, inbound_car, outbound_car, qos_profile, update_interval) VALUES
('1668938207749279745', '100m', '@cu', 'test', 0000000000, 0, 'admin', '2023-06-14 19:07:30', NULL, '2023-10-09 16:21:11', 1, 0, 0, 0, 102400, 51200, '', 900),
('1704057760273489922', '1000m', '@cu', 'test', 0000000000, 0, 'admin', '2023-09-19 17:00:04', NULL, '2023-10-09 16:21:11', 1, 0, 0, 0, 512000, 1024000, '', 1800),
('1704057844033740802', '10m', '@cu', 'test', 0000000000, 0, 'admin', '2023-09-19 17:00:24', NULL, '2023-10-09 16:21:11', 1, 0, 0, 0, 5120, 10240, '', 1800),
('1704057976791851010', '500m', '@cu', 'test', 0000000000, 0, 'admin', '2023-09-19 17:00:56', NULL, '2023-10-09 16:21:11', 1, 0, 0, 0, 256000, 512000, '', 1800),
('1711380434389655553', 'SR10000687', '@cu', '88888888', 0000000000, 0, 'admin', '2023-10-09 00:00:00', '2099-12-31 23:59:59', '2023-10-09 21:57:46', 1, 0, 0, 0, 51200, 102400, '', 1800),
('1711383169310744578', '60007085', '@cu', '666666', 0000000000, 0, 'admin', '2023-10-08 22:08:16', '2099-12-31 23:59:59', '2023-10-09 22:08:38', 1, 0, 0, 0, 51200, 102400, '', 1800);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;