FROM nginx:latest
RUN apt-get update
RUN apt-get install nginx
RUN apt-get -y install vim 
COPY ./docker-entrypoint.sh /
COPY ./nginx.conf /etc/nginx/
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD tail -f /dev/null


