/* Automatically generated by "build-radpaths-h" */
#define LOGDIR		"/home/radius/radius/var/log/radius"
#define LIBDIR		"/home/radius/radius/lib"
#define RADDBDIR	"/home/radius/radius/etc/raddb"
#define RUNDIR		"/home/radius/radius/var/run"
#define SBINDIR		"/home/radius/radius/sbin"
#define RADIR		"/home/radius/radius/var/log/radius/radacct"
#define DICTDIR		"/home/radius/radius/share/freeradius"
